.TH 9IT-OBJUTILS 3 2020-12-31 9it-0.1
.SH NAME
write_blob, write_tree
.SH DESCRIPTION
This is the developer man page for the header file objutils.h. For 9it usage, please refer to 9it (1).
.SH SYNOPSIS
#include "headers/objutils.h"

\fBchar* write_blob(char* file_path);\fP
\fBchar* write_tree(Tree* tree);\fP
char* write_commit(Commit* commit);
.SH DESCRIPTION
