.TH 9IT 1 2021-01-03 9it-0.1
.SH NAME
9it \- totally not git!
.SH SYNOPSIS
.B 9it 
[9it options] <subcommand> [subcommand options]
.SH DESCRIPTION
9it is a simple version control system written in C.
.SH OPTIONS
.TP
.BR \-\-help
Displays a list of subcommands.
.SH SUBCOMMANDS
.SS add
Adds files to the index. If a directory is passed, it will recursively add all files in that directory.
.SS cat
Displays helpful information about the 9it objects in the objects directory.
.TP
\fB\-p\fR <\fIOBJECT-FILE\fP>, \fB\-\-print=\fR\fIOBJECT-FILE\fP
Prints out the contents of object file in human readable text.
.TP
\fB\-t\fR <\fIOBJECT-FILE\fP>, \fB\-\-type=\fR\fIOBJECT-FILE\fP
Prints out the type of the object file. Possible ones are "Blob", "Tree", and "Commit".
.SS commit
Commit changes, by default, this opens your the editor set by you EDITOR environment variable and prompts you to enter a commit message. Also keep in mind that the NINEIT_USERNAME environment variable needs to be set when calling this.
.TP
\fB\-m\fR <\fIMESSAGE\fP> \fB\-\-message=\fR\fIMESSAGE\fP
Allows you to enter a commit message inline. Remember to wrap the message in quotes if you want to use spaces.

.SS init
Initialize a new 9it repository in the current working directory. By default, the 9it required files are placed in a hidden .9it directory.
.TP
\fB\-b\fR, \fB\-\-bare\fR
Dumps the contents of the .9it directory into the current directory. This option is mostly used on the server side.
.SH FILES/DIRECTORY STRUCTURE
If 9it was initialized without the bare option, then 9it will create a hidden .9it directory inside the current working directory, which contains all the files required.
Generally, the user does not need to worry about the contents of this directory, but an explanation is included here nonetheless.
.TP
.BR objects/
.TP
.BR refs/
.SH ENVIRONMENT
.TP
.BR NINEIT_USER_NAME
This needs to be set in order to commit
.SH AUTHORS
9it was written by Daniel Liu and Mark "Zhehai" Zhang.
.SH REPORTING BUGS
Please open an issue at https://github.com/NaiveGit/9it-cli
